### ISSUE TITLE
qjs prints 'messy code'

### ISSUE THREAD

**Issue by lab4quant** [mengmo/QuickJS-Windows-Build#1]
system: windows 10 64-bit

Hello, 
after downloading, run `qjs` from `CMD` and type below simple commands, there're many messy code...
but after checking thoroughly, the output is same as `node.js`

how to get rid of those obviouse messy stuff? thanks!

```sh
QuickJS - Type "\h" for help
qjs > let x = 1
[32;1ml[0m[J[D[32;1mle[0m[J[2D[37;1mlet[0m[J[3D[37;1mlet[0m[32;1m [0m[J[4D[37;1mlet[0m[32;1m [0m[32;1mx[0m[J[5D[37;1mlet[0m[32;1m [0m[32;1mx[0m[32;1m [0m[J[6D[37;1mlet[0m[32;1m [0m[32;1mx[0m[32;1m =[0m[J[7D[37;1mlet[0m[32;1m [0m[32;1mx[0m[32;1m = [0m[J[8D[37;1mlet[0m[32;1m [0m[32;1mx[0m[32;1m = [0m[32m1[0m[J
[37;1mundefined
[0mqjs > x
[32;1mx[0m[J
[37;1m1
[0mqjs > \h
[32;1m\[0m[J[D[32;1m\[0m[32;1mh[0m[J
\h          this help
\x          hexadecimal number display
\d         *decimal number display
\t          toggle timing display
\clear      clear the terminal
\q          exit
qjs > 1*2
[32m1[0m[J[D[32m1[0m[32;1m*[0m[J[2D[32m1[0m[32;1m*[0m[32m2[0m[J
[37;1m2
[0mqjs > ^C
```

**Comment by mengmo** [comment]
Use a terminal that support colored output like MSYS2

What's more, you can refer to
[How to echo with different colors in the Windows command line](https://stackoverflow.com/questions/2048509/how-to-echo-with-different-colors-in-the-windows-command-line)
and [Allow terminal color setting](https://github.com/microsoft/terminal/issues/81)

**Comment by lab4quant** [comment]
@mengmo, great, thanks, it's working with git-bash
