### ISSUE TITLE
missing libquickjsbn.dll in last  prebuilt binary releases  

### ISSUE THREAD

**Issue by btx638** [mengmo/QuickJS-Windows-Build#2]
missing libquickjsbn.dll in last  prebuilt binary releases

**Comment by mengmo** [comment]
@btx638 Sorry!
Because of the following change, there is **no difference** between **libquickjs.dll** and **libquickjsbn.dll**
> always compile the bignum code. Added '--bignum' option to qjs.

More reference [[quickjs-devel] Re: New release](https://www.freelists.org/post/quickjs-devel/New-release,91)

I've modified the latest release dexcription.

**Comment by btx638** [comment]
thanks
